module.exports = [
  { name: "Aislinn_Wishart" },
  { name: "Amae_Koromo" },
  { name: "Anetai_Toyone", isBeta: true },
  { name: "Arakawa_Kei" },
  { name: "Atago_Hiroe", isBeta: true },
  { name: "Atarashi_Ako" },
  { name: "Choe_Myeonghwa" },
  { name: "Ezaki_Hitomi", isBeta: true },
  { name: "Fukuji_Mihoko", isBeta: true },
  { name: "Hanada_Kirame", isBeta: true },
  { name: "Hao_Huiyu", isBeta: true },
  { name: "Haramura_Nodoka" },
  { name: "Hirose_Sumire", isBeta: true },
  { name: "Ikeda_Kana", isBeta: true },
  { name: "Inoue_Jun", isBeta: true },
  { name: "Iwato_Kasumi", isBeta: true },
  { name: "Jindai_Komaki" },
  { name: "Kainou_Yoshiko", isBeta: true },
  { name: "Kajiki_Yumi" },
  { name: "Kakura_Kurumi", isBeta: true },
  { name: "Kanbara_Satomi", isBeta: true },
  { name: "Karijuku_Tomoe" },
  { name: "Kataoka_Yuuki" },
  { name: "Kosegawa_Shiromi", isBeta: true },
  { name: "Kunihiro_Hajime", isBeta: true },
  { name: "Shirouzu_Mairu", betaHimeko: true },
  { name: "Mase_Yuuko" },
  { name: "Matano_Seiko" },
  { name: "Matsumi_Kuro" },
  { name: "Matsumi_Yuu" },
  { name: "Maya_Yukiko" },
  { name: "Megan_Davin", isBeta: true },
  { name: "Miyanaga_Saki" },
  { name: "Miyanaga_Teru" },
  { name: "Nanpo_Kazue" },
  { name: "Nelly_Virsaladze", isBeta: true },
  { name: "Onjouji_Toki" },
  { name: "Oohoshi_Awai", isBeta: true },
  { name: "Ryuumonbuchi_Touka" },
  { name: "Sagimori_Arata", isBeta: true },
  { name: "Sawamura_Tomoki" },
  { name: "Senoo_Kaori" },
  { name: "Shibuya_Takami", isBeta: true },
  { name: "Shimizudani_Ryuuka" },
  { name: "Someya_Mako", isBeta: true },
  { name: "Takakamo_Shizuno" },
  { name: "Takei_Hisa", isBeta: true },
  { name: "Takimi_Haru" },
  { name: "Toyouko_Momoko" },
  { name: "Tsujigaito_Satoha", isBeta: true },
  { name: "Usuzawa_Sae" },
  { name: "Usuzumi_Hatsumi" },
  { name: "Ueshige_Suzu" },
  { name: "Yumeno_Maho" },
  { name: "Ataga_Kinue", isBeta: true },
  { name: "Funakubo_Hiroko", isBeta: true },
  { name: "Iwadate_Yuan", isBeta: true },
  { name: "Motouchi_Naruka", isBeta: true },
  { name: "Shishihara_Sawaya", isBeta: true },
  { name: "Suehara_Kyouko", isBeta: true },
  { name: "Ueshige_Suzu", isBeta: true },
  { name: "Yae_Kobashiri", isBeta: true },
  { name: "Yoshitome_Miharu", isBeta: true },
]